# Generated by Django 4.0.2 on 2023-08-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0015_item_offer_price_alter_item_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='item_total',
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='checkout_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('item_total', models.FloatField(blank=True, null=True)),
                ('item_price', models.FloatField(blank=True, null=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MalieakalApp.checkout')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MalieakalApp.item')),
            ],
        ),
    ]
