# Generated by Django 4.0.2 on 2023-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0016_remove_checkout_item_name_remove_checkout_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='qty',
        ),
        migrations.AddField(
            model_name='checkout_item',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
