# Generated by Django 4.0.2 on 2023-08-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0018_remove_checkout_item_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MalieakalApp.profile_user'),
        ),
    ]
