# Generated by Django 4.0.2 on 2023-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0019_checkout_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
