# Generated by Django 4.0.2 on 2023-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0021_profile_user_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
    ]
